from motor.motor_asyncio import AsyncIOMotorClient
import asyncio

client = AsyncIOMotorClient("mongodb://localhost:27017")
db = client["daraz_clone"]
products_collection = db["products"]

async def seed_products():
    products = [
        {
            "name": "TWS I12 M19 Airpods",
            "price": 1999,
            "discount_percent": 69,
            "discounted_price": 621,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash1.jpg"],
            "category": "Electronics",
            "quantity": 50,
            "rating": 4.5,
            "review_count": 120,
            "tags": ["earbuds", "wireless"]
        },
        {
            "name": "Newmine Bluetooth Airpods",
            "price": 1999,
            "discount_percent": 70,
            "discounted_price": 597,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash2.jpg"],
            "category": "Electronics",
            "quantity": 40,
            "rating": 4.4,
            "review_count": 98,
            "tags": ["audio", "bluetooth"]
        },
        {
            "name": "M10 A6s F2 Earbuds",
            "price": 1999,
            "discount_percent": 68,
            "discounted_price": 634,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash3.jpg"],
            "category": "Electronics",
            "quantity": 35,
            "rating": 4.3,
            "review_count": 85,
            "tags": ["earphones", "sport"]
        },
        {
            "name": "Electric Kitchen Lighter",
            "price": 3000,
            "discount_percent": 62,
            "discounted_price": 1130,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash5.jpg"],
            "category": "Home",
            "quantity": 20,
            "rating": 4.2,
            "review_count": 60,
            "tags": ["kitchen", "lighter"]
        },
        {
            "name": "Wireless Headset 5.3",
            "price": 2999,
            "discount_percent": 76,
            "discounted_price": 705,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash6.jpg"],
            "category": "Electronics",
            "quantity": 30,
            "rating": 4.6,
            "review_count": 150,
            "tags": ["headset", "wireless"]
        },
        {
            "name": "Men's Summer Tracksuit",
            "price": 1500,
            "discount_percent": 50,
            "discounted_price": 750,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash4.jpg"],
            "category": "Fashion",
            "quantity": 25,
            "rating": 4.3,
            "review_count": 60,
            "tags": ["tracksuit", "men"]
        },
        {
            "name": "Kids Printed T-Shirt",
            "price": 800,
            "discount_percent": 45,
            "discounted_price": 440,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash1.jpg"],
            "category": "Kids",
            "quantity": 40,
            "rating": 4.6,
            "review_count": 90,
            "tags": ["kids", "tshirt"]
        },
        {
            "name": "Pro White TWS Airpods",
            "price": 2999,
            "discount_percent": 74,
            "discounted_price": 770,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash2.jpg"],
            "category": "Electronics",
            "quantity": 45,
            "rating": 4.7,
            "review_count": 110,
            "tags": ["airpods", "bluetooth"]
        },
        {
            "name": "Stylish Sandals for Men",
            "price": 1499,
            "discount_percent": 77,
            "discounted_price": 349,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash3.jpg"],
            "category": "Fashion",
            "quantity": 60,
            "rating": 4.4,
            "review_count": 125,
            "tags": ["sandals", "men"]
        },
        {
            "name": "Night Suit for Women",
            "price": 1999,
            "discount_percent": 60,
            "discounted_price": 799,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash4.jpg"],
            "category": "Beauty",
            "quantity": 35,
            "rating": 4.5,
            "review_count": 95,
            "tags": ["nightwear", "women"]
        },
        {
            "name": "Gaming Mouse X300",
            "price": 1200,
            "discount_percent": 55,
            "discounted_price": 540,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash7.jpg"],
            "category": "Electronics",
            "quantity": 60,
            "rating": 4.4,
            "review_count": 140,
            "tags": ["gaming", "mouse", "electronics"]
        },
        {
            "name": "Yoga Mat 6mm Thickness",
            "price": 1000,
            "discount_percent": 40,
            "discounted_price": 600,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash8.jpg"],
            "category": "Sports",
            "quantity": 40,
            "rating": 4.2,
            "review_count": 75,
            "tags": ["yoga", "fitness"]
        },
        {
            "name": "Bluetooth Speaker Portable",
            "price": 2500,
            "discount_percent": 65,
            "discounted_price": 875,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash9.jpg"],
            "category": "Electronics",
            "quantity": 25,
            "rating": 4.6,
            "review_count": 130,
            "tags": ["speaker", "bluetooth", "audio"]
        },
        {
            "name": "Leather Wallet Men",
            "price": 1600,
            "discount_percent": 50,
            "discounted_price": 800,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash10.jpg"],
            "category": "Fashion",
            "quantity": 45,
            "rating": 4.3,
            "review_count": 85,
            "tags": ["wallet", "leather", "men"]
        },
        {
            "name": "Kids Cartoon Backpack",
            "price": 1800,
            "discount_percent": 48,
            "discounted_price": 936,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash11.jpg"],
            "category": "Kids",
            "quantity": 30,
            "rating": 4.5,
            "review_count": 105,
            "tags": ["backpack", "kids", "cartoon"]
        },
        {
            "name": "Hair Straightener Pro",
            "price": 3200,
            "discount_percent": 60,
            "discounted_price": 1280,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash12.jpg"],
            "category": "Beauty",
            "quantity": 20,
            "rating": 4.7,
            "review_count": 95,
            "tags": ["hair", "beauty", "straightener"]
        },
        {
            "name": "Men's Running Shoes",
            "price": 2500,
            "discount_percent": 55,
            "discounted_price": 1125,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash13.jpg"],
            "category": "Fashion",
            "quantity": 50,
            "rating": 4.6,
            "review_count": 110,
            "tags": ["shoes", "running", "men"]
        },
        {
            "name": "LED Desk Lamp",
            "price": 1800,
            "discount_percent": 48,
            "discounted_price": 936,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash14.jpg"],
            "category": "Home",
            "quantity": 30,
            "rating": 4.4,
            "review_count": 80,
            "tags": ["lamp", "desk", "LED"]
        },
        {
            "name": "Wireless Charging Pad",
            "price": 2200,
            "discount_percent": 60,
            "discounted_price": 880,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash15.jpg"],
            "category": "Electronics",
            "quantity": 40,
            "rating": 4.5,
            "review_count": 125,
            "tags": ["charger", "wireless", "electronics"]
        },
        {
            "name": "Kids Toy Car Set",
            "price": 1500,
            "discount_percent": 50,
            "discounted_price": 750,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash16.jpg"],
            "category": "Kids",
            "quantity": 35,
            "rating": 4.7,
            "review_count": 90,
            "tags": ["toys", "kids", "car"]
        },
        {
            "name": "Organic Face Cream",
            "price": 1200,
            "discount_percent": 54,
            "discounted_price": 552,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash17.jpg"],
            "category": "Beauty",
            "quantity": 25,
            "rating": 4.6,
            "review_count": 85,
            "tags": ["skin", "beauty", "cream"]
        },
        {
            "name": "Smart Watch X5",
            "price": 3500,
            "discount_percent": 62,
            "discounted_price": 1330,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash18.jpg"],
            "category": "Electronics",
            "quantity": 40,
            "rating": 4.7,
            "review_count": 115,
            "tags": ["smartwatch", "wearable"]
        },
        {
            "name": "Men's Casual Shirt",
            "price": 2000,
            "discount_percent": 55,
            "discounted_price": 900,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash19.jpg"],
            "category": "Fashion",
            "quantity": 60,
            "rating": 4.4,
            "review_count": 70,
            "tags": ["shirt", "men", "casual"]
        },
        {
            "name": "Wireless Earbuds A7",
            "price": 2700,
            "discount_percent": 63,
            "discounted_price": 999,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash20.jpg"],
            "category": "Electronics",
            "quantity": 50,
            "rating": 4.5,
            "review_count": 130,
            "tags": ["earbuds", "wireless", "audio"]
        },
        {
            "name": "Kids School Shoes",
            "price": 1800,
            "discount_percent": 50,
            "discounted_price": 900,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash21.jpg"],
            "category": "Kids",
            "quantity": 40,
            "rating": 4.6,
            "review_count": 95,
            "tags": ["shoes", "kids", "school"]
        },
        {
            "name": "Home Cleaning Vacuum",
            "price": 4000,
            "discount_percent": 58,
            "discounted_price": 1680,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash22.jpg"],
            "category": "Home",
            "quantity": 15,
            "rating": 4.3,
            "review_count": 65,
            "tags": ["vacuum", "cleaning"]
        },
        {
            "name": "Women's Running Sneakers",
            "price": 2800,
            "discount_percent": 54,
            "discounted_price": 1288,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash23.jpg"],
            "category": "Fashion",
            "quantity": 35,
            "rating": 4.5,
            "review_count": 85,
            "tags": ["shoes", "women", "running"]
        },
        {
            "name": "Bluetooth Fitness Tracker",
            "price": 3000,
            "discount_percent": 60,
            "discounted_price": 1200,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash24.jpg"],
            "category": "Electronics",
            "quantity": 50,
            "rating": 4.4,
            "review_count": 110,
            "tags": ["fitness", "tracker", "wearable"]
        },
        {
            "name": "Electric Hair Dryer",
            "price": 2300,
            "discount_percent": 50,
            "discounted_price": 1150,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash25.jpg"],
            "category": "Beauty",
            "quantity": 30,
            "rating": 4.3,
            "review_count": 70,
            "tags": ["hair", "dryer", "beauty"]
        },
        {
            "name": "Men's Leather Belt",
            "price": 1400,
            "discount_percent": 48,
            "discounted_price": 728,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash26.jpg"],
            "category": "Fashion",
            "quantity": 60,
            "rating": 4.5,
            "review_count": 100,
            "tags": ["belt", "leather", "men"]
        },
        {
            "name": "Kids Bicycle Helmet",
            "price": 1600,
            "discount_percent": 52,
            "discounted_price": 768,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash27.jpg"],
            "category": "Kids",
            "quantity": 40,
            "rating": 4.7,
            "review_count": 90,
            "tags": ["helmet", "kids", "safety"]
        },
        {
            "name": "Smartphone Tripod Stand",
            "price": 1100,
            "discount_percent": 45,
            "discounted_price": 605,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash28.jpg"],
            "category": "Electronics",
            "quantity": 35,
            "rating": 4.4,
            "review_count": 83,
            "tags": ["tripod", "smartphone", "photography"]
        },
        {
            "name": "Portable Power Bank 20000mAh",
            "price": 3200,
            "discount_percent": 60,
            "discounted_price": 1280,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash29.jpg"],
            "category": "Electronics",
            "quantity": 45,
            "rating": 4.5,
            "review_count": 120,
            "tags": ["powerbank", "portable", "battery"]
        },
        {
            "name": "Wireless Keyboard and Mouse Combo",
            "price": 2600,
            "discount_percent": 55,
            "discounted_price": 1170,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash30.jpg"],
            "category": "Electronics",
            "quantity": 50,
            "rating": 4.3,
            "review_count": 105,
            "tags": ["keyboard", "mouse", "wireless"]
        },
        {
            "name": "Women's Summer Hat",
            "price": 1200,
            "discount_percent": 50,
            "discounted_price": 600,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash31.jpg"],
            "category": "Fashion",
            "quantity": 40,
            "rating": 4.6,
            "review_count": 90,
            "tags": ["hat", "women", "summer"]
        },
        {
            "name": "Children's Story Books Set",
            "price": 1000,
            "discount_percent": 40,
            "discounted_price": 600,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash32.jpg"],
            "category": "Kids",
            "quantity": 55,
            "rating": 4.8,
            "review_count": 140,
            "tags": ["books", "kids", "stories"]
        },
        {
            "name": "Electric Kettle 1.5L",
            "price": 3500,
            "discount_percent": 60,
            "discounted_price": 1400,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash33.jpg"],
            "category": "Home",
            "quantity": 35,
            "rating": 4.5,
            "review_count": 70,
            "tags": ["kitchen", "electric", "kettle"]
        },
        {
            "name": "Men's Leather Shoes",
            "price": 4000,
            "discount_percent": 52,
            "discounted_price": 1920,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash34.jpg"],
            "category": "Fashion",
            "quantity": 30,
            "rating": 4.4,
            "review_count": 95,
            "tags": ["leather", "shoes", "men"]
        },
        {
            "name": "Portable Mini Fan",
            "price": 1000,
            "discount_percent": 45,
            "discounted_price": 550,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash35.jpg"],
            "category": "Home",
            "quantity": 60,
            "rating": 4.3,
            "review_count": 85,
            "tags": ["fan", "portable", "home"]
        },
        {
            "name": "Smart Home WiFi Plug",
            "price": 1500,
            "discount_percent": 50,
            "discounted_price": 750,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash36.jpg"],
            "category": "Electronics",
            "quantity": 45,
            "rating": 4.6,
            "review_count": 110,
            "tags": ["smart", "plug", "wifi"]
        },
        {
            "name": "Cotton Men's Socks (5 Pairs)",
            "price": 800,
            "discount_percent": 40,
            "discounted_price": 480,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash37.jpg"],
            "category": "Fashion",
            "quantity": 70,
            "rating": 4.4,
            "review_count": 115,
            "tags": ["socks", "men", "cotton"]
        },
        {
            "name": "Kids Learning Tablet",
            "price": 3500,
            "discount_percent": 58,
            "discounted_price": 1470,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash38.jpg"],
            "category": "Kids",
            "quantity": 25,
            "rating": 4.5,
            "review_count": 130,
            "tags": ["tablet", "kids", "learning"]
        },
        {
            "name": "Men's Formal Blazer",
            "price": 5500,
            "discount_percent": 60,
            "discounted_price": 2200,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash39.jpg"],
            "category": "Fashion",
            "quantity": 20,
            "rating": 4.7,
            "review_count": 65,
            "tags": ["blazer", "men", "formal"]
        },
        {
            "name": "Hair Curling Iron",
            "price": 3200,
            "discount_percent": 56,
            "discounted_price": 1408,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash40.jpg"],
            "category": "Beauty",
            "quantity": 30,
            "rating": 4.6,
            "review_count": 80,
            "tags": ["hair", "curling", "beauty"]
        },
        {
            "name": "Wireless Security Camera",
            "price": 4500,
            "discount_percent": 60,
            "discounted_price": 1800,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash41.jpg"],
            "category": "Electronics",
            "quantity": 25,
            "rating": 4.7,
            "review_count": 90,
            "tags": ["camera", "security", "wireless"]
        },
        {
            "name": "Men's Winter Gloves",
            "price": 1500,
            "discount_percent": 50,
            "discounted_price": 750,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash42.jpg"],
            "category": "Fashion",
            "quantity": 40,
            "rating": 4.3,
            "review_count": 70,
            "tags": ["gloves", "men", "winter"]
        },
        {
            "name": "Outdoor Camping Tent",
            "price": 7000,
            "discount_percent": 55,
            "discounted_price": 3150,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash43.jpg"],
            "category": "Sports",
            "quantity": 15,
            "rating": 4.6,
            "review_count": 60,
            "tags": ["camping", "tent", "outdoors"]
        },
        {
            "name": "Smartphone Car Mount Holder",
            "price": 1200,
            "discount_percent": 50,
            "discounted_price": 600,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash44.jpg"],
            "category": "Electronics",
            "quantity": 55,
            "rating": 4.4,
            "review_count": 95,
            "tags": ["car", "mount", "smartphone"]
        },
        {
            "name": "Electric Garlic Cutter",
            "price": 1400,
            "discount_percent": 43,
            "discounted_price": 798,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash45.jpg"],
            "category": "Home",
            "quantity": 30,
            "rating": 4.3,
            "review_count": 80,
            "tags": ["kitchen", "cutter", "electric"]
        },
        {
            "name": "Women’s Casual Handbag",
            "price": 2800,
            "discount_percent": 52,
            "discounted_price": 1344,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash46.jpg"],
            "category": "Fashion",
            "quantity": 40,
            "rating": 4.7,
            "review_count": 105,
            "tags": ["handbag", "women", "casual"]
        },
        {
            "name": "Wireless Mouse M90",
            "price": 1500,
            "discount_percent": 50,
            "discounted_price": 750,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash47.jpg"],
            "category": "Electronics",
            "quantity": 50,
            "rating": 4.5,
            "review_count": 115,
            "tags": ["mouse", "wireless", "electronics"]
        },
        {
            "name": "Kids Sports Watch",
            "price": 1200,
            "discount_percent": 45,
            "discounted_price": 660,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash48.jpg"],
            "category": "Kids",
            "quantity": 60,
            "rating": 4.6,
            "review_count": 100,
            "tags": ["watch", "kids", "sports"]
        },
        {
            "name": "Digital Kitchen Scale",
            "price": 1000,
            "discount_percent": 40,
            "discounted_price": 600,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash49.jpg"],
            "category": "Home",
            "quantity": 35,
            "rating": 4.3,
            "review_count": 75,
            "tags": ["kitchen", "scale", "digital"]
        },
        {
            "name": "Men's Cycling Helmet",
            "price": 3000,
            "discount_percent": 55,
            "discounted_price": 1350,
            "image_urls": ["https://img.lazcdn.com/us/images/ims-web/flash50.jpg"],
            "category": "Sports",
            "quantity": 20,
            "rating": 4.6,
            "review_count": 60,
            "tags": ["helmet", "cycling", "men"]
        }
    ]

    await products_collection.insert_many(products)
    print("✅ 50 products seeded successfully!")

asyncio.run(seed_products())
